services:
  mofip-docker-dind:
    image: docker:dind

  mofip-jenkins:
    image: mofip-jenkins
    depends_on:
      - mofip-docker-dind
    restart: on-failure

  mofip-devlinux:
    image: mofip-devlinux
    restart: on-failure

  mofip-localdevlinux:
    image: mofip-devlinux
    container_name: mofip-localdevlinux
    volumes:
      - ../:/mofip
    working_dir: /mofip
    ports:
      - "$MOFIP_LOCALDEV_PORT_SSH:22"
    restart: on-failure
    tty: true

  mofip-serverlinux:
    image: mofip-serverlinux
    restart: on-failure

networks:
  mofip-jenkins:
    name: mofip-jenkins
  mofip-devlinux:
    name: mofip-devlinux
  mofip-serverlinux:
    name: mofip-serverlinux

volumes:
  mofip-jenkins-docker-certs:
  mofip-jenkins-data:
