services:
  mofip-docker-dind:
    image: docker:dind

  mofip-jenkins:
    image: mofip-jenkins
    depends_on:
      - mofip-docker-dind
    restart: on-failure

  mofip-devlinux:
    image: mofip-devlinux

  mofip-localdevlinux:
    image: mofip-devlinux
    container_name: mofip-localdevlinux
    volumes:
      - ../app:/app
    working_dir: /app
    tty: true

networks:
  mofip-jenkins:
    name: mofip-jenkins
  mofip-devlinux:
    name: mofip-devlinux

volumes:
  mofip-jenkins-docker-certs:
  mofip-jenkins-data:
