services:
  mofip-devlinux:
    build:
      context: ./devlinux
      dockerfile: Dockerfile
    container_name: mofip-devlinux
    networks:
      - mofip-devlinux
    ports:
      - "$MOFIP_DEV_PORT_SSH:22"
    tty: true
